export const STATUS_LOADING = 'STATUS_LOADING'
export const STATUS_LOADED = 'STATUS_LOADED'
export const STATUS_ERROR = 'STATUS_ERROR'

export const NEAR_ME = 'NEAR_ME'
export const WITHIN_INDIA = 'WITHIN_INDIA'
export const TAKE_ME_PLACES = 'TAKE_ME_PLACES'
export const BEACH = 'BEACH'
export const HILL_STATION = 'HILL_STATION'
export const API_BASE_URL = 'https://svc-flashpacker-api.herokuapp.com/api/v1'
